#!/bin/bash

set -e

message=(
    "\033[0;32m"
    "The 'batch adjustment overview' and 'confounded network' images"
    "were made in Google Drawings and can't be generated by code.\n"
    "See the figures README for links to the Drawings."
    "\033[0m"
)
echo -e ${message[@]}
